spring:
  application:
    name: webbandogiadung
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

postgres:
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSourcedial

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update

sqlserver:
  datasource:
    url: ${SQLSERVER_URL:jdbc:sqlserver://localhost:1433;databaseName=datamart_db;encrypt=true;trustServerCertificate=true;sendStringParametersAsUnicode=false}
    username: ${SQLSERVER_USER:sa}
    password: ${SQLSERVER_PASSWORD:YourStrong@Passw0rd}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        hbm2ddl:
          auto: validate

jwt:
  signerKey: eyjHbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9dasdasfasfasd
  expireTime: 3600
  refreshTime: 100000

integration:
  mailer:
    apiKey: mlsn.2f3b34ec49a82633b41852b2fae24f2d01df4a235517b1e1e4780864d53d3c97
  cloudinary:
    name: dm4m3hibo
    apiKey: 829885551835997
    apiSecret: --kvV76wCaVXIWMOnt7eljZyFb8



