spring:
  application:
    name:
      CostumeForRent
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${POSTGRESQL_HOST:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DATABASE:postgres}
    username: ${POSTGRESQL_USER:admin}
    password: ${POSTGRESQL_PASS:123456}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    generate-ddl: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
jwt:
  signerKey: eyjHbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9dasdasfasfasd
  expireTime: 3600
  refreshTime: 100000

integration:
  mailer:
    apiKey: mlsn.2f3b34ec49a82633b41852b2fae24f2d01df4a235517b1e1e4780864d53d3c97
  cloudinary:
    name: dm4m3hibo
    apiKey: 829885551835997
    apiSecret: --kvV76wCaVXIWMOnt7eljZyFb8



