services:
  postgres:

    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  sqlserver:
    container_name: sqlserver_container
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    user: "0:0"
    restart: unless-stopped
  spring-app:
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
    container_name: spring_app
    depends_on:
      - postgres
      - sqlserver
    environment:
      SPRING_PROFILES_ACTIVE: docker

      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456

      SQLSERVER_URL: jdbc:sqlserver://sqlserver:1433;databaseName=datamart_db
      SQLSERVER_USER: sa
      SQLSERVER_PASSWORD: YourStrong@Passw0rd
    ports:
      - "8080:8080"
volumes:
  postgres:
  sqlserver_data:
